name: Compress Images

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.png'

jobs:
  compress-images:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    # Only run on Pull Requests within the same repository, not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress PR Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '85'
          jpegProgressive: false
          pngQuality: '80'
          webpQuality: '85'
          avifQuality: '75'
          ignorePaths: 'node_modules/**'
